name: Build LaTeX document

on:
  push:
    branches:
      - 'master'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: report.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: report.pdf

      - name: Commit report
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add report.pdf
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Update report.pdf'
            git push
          fi
